//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace blqw.PT
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 分析器容器
	/// </summary>
	public interface IProfilerCollection  : ICollection<ITestProfiler>
	{
		/// <summary>
		/// 设置所有分析器的间隔时间
		/// </summary>
		void SetInterval(TimeSpan value);

        /// <summary>
        /// 开始运行所有分析器
        /// </summary>
        /// <param name="result"></param>
        void Start(ITestResult result);

        /// <summary>
        /// 终止所有分析器
        /// </summary>
        void Stop();
	}
}

