//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace blqw.PT
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 测试分析器
	/// </summary>
	/// <remarks>负责分析记录各种数值</remarks>
	public interface ITestProfiler 
	{
		ITestResult TestResult { get;set; }

		string Value { get;set; }

		/// <summary>
		/// 分析器的刷新时间
		/// </summary>
		TimeSpan Interval { get;set; }

	}
}

