//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace blqw.PT
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Text;

    /// <summary>
    /// 测试器接口
    /// </summary>
    /// <remarks>各种不同方式启动测试任务</remarks>
    public interface ITester 
	{
        /// <summary>
        /// 执行测试的对象
        /// </summary>
		ITestWorker Worker { get;set; }

		/// <summary>
		/// 测试执行的次数
		/// </summary>
		int TestingCount { get;set; }

		/// <summary>
		/// 线程数
		/// </summary>
		int ThreadCount { get;set; }

		/// <summary>
		/// 线程执行次数均分
		/// </summary>
		bool Equally { get;set; }

		/// <summary>
		/// 两次测试之间的时间间隔
		/// </summary>
		TimeSpan TestingDelay { get;set; }

        /// <summary>
        /// 监听器集合
        /// </summary>
        IProfilerCollection Profilers { get;set; }
        
		/// <summary>
		/// 测试前的预热
		/// </summary>
		/// <param name="count">预热次数</param>
		void Preheat(int count = 1);

		/// <summary>
		/// 开始测试
		/// </summary>
		ITestResult Run();

        /// <summary>
        /// 设置或获取测试信息的输出流
        /// </summary>
        TextWriter Output { get; set; }

        /// <summary>
        /// 取消当前测试
        /// </summary>
        /// <param name="async">异步执行</param>
        void Cancel(bool async = false);
    }
}

