//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成
//     如果重新生成代码，将丢失对此文件所做的更改。
// </auto-generated>
//------------------------------------------------------------------------------
namespace blqw.PT
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	/// <summary>
	/// 测试任务结果
	/// </summary>
	/// <remarks>测试任务结果</remarks>
	public interface ITestResult 
	{
		/// <summary>
		/// 已完成的数量
		/// </summary>
		int Completed { get; }

		/// <summary>
		/// 测试任务耗时
		/// </summary>
		TimeSpan Elapsed { get;}

		/// <summary>
		/// 失败的数量
		/// </summary>
		int Failed { get;}

		/// <summary>
		/// 成功的数量
		/// </summary>
		int Succeeded { get; }

        /// <summary>
        /// 测试失败时引发事件
        /// </summary>
        event TestFailHandler OnFailed;

        /// <summary>
        /// 测试成功时引发事件
        /// </summary>
        event TestSucceedHandler OnSucceeded;

    }
}

